server:
  port: 8080
  

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidosDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # use "none", "validate", "create", "create-drop", conforme necessário
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
